-- Tabla staging para recibir la carga desde Oracle Forms
-- Compatible con Oracle 11g+

CREATE SEQUENCE SEQ_STG_CARGA_XLS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE STG_CARGA_XLS (
  ID_CARGA      NUMBER PRIMARY KEY,
  CODIGO        VARCHAR2(100),
  DESCRIPCION   VARCHAR2(500),
  CANTIDAD      NUMBER(18,4),
  PRECIO        NUMBER(18,4),
  FILA_EXCEL    NUMBER,
  FECHA_CARGA   DATE DEFAULT SYSDATE,
  ESTADO        VARCHAR2(20) DEFAULT 'PENDIENTE',
  MENSAJE_ERROR VARCHAR2(4000)
);

CREATE OR REPLACE TRIGGER TRG_STG_CARGA_XLS_BI
BEFORE INSERT ON STG_CARGA_XLS
FOR EACH ROW
WHEN (NEW.ID_CARGA IS NULL)
BEGIN
  SELECT SEQ_STG_CARGA_XLS.NEXTVAL INTO :NEW.ID_CARGA FROM DUAL;
END;
/

CREATE INDEX IDX_STG_CARGA_XLS_COD ON STG_CARGA_XLS (CODIGO);
CREATE INDEX IDX_STG_CARGA_XLS_FEC ON STG_CARGA_XLS (FECHA_CARGA);

COMMENT ON TABLE STG_CARGA_XLS IS
  'Staging de carga de Excel desde Oracle Forms (CLIENT_OLE2)';

-- Ejemplo: pasar de staging a tabla final
/*
INSERT INTO PRODUCTOS (CODIGO, DESCRIPCION, CANTIDAD, PRECIO)
SELECT CODIGO, DESCRIPCION, CANTIDAD, PRECIO
  FROM STG_CARGA_XLS
 WHERE ESTADO = 'PENDIENTE'
   AND CODIGO IS NOT NULL;

UPDATE STG_CARGA_XLS
   SET ESTADO = 'PROCESADO'
 WHERE ESTADO = 'PENDIENTE';

COMMIT;
*/
